spring:
  profiles:
    active: local
  mvc:
    throw-exception-if-no-handler-found: true

server-config:
  gpms-url: "http://192.168.20.6:13000"
  ngis-url: "http://localhost:7777"
  server-key: "GATESVR1"
  check-time: 30
  breaker-command:
    open: "GATE UP"
    close: "GATE DOWN"
    uplock: "GATE UPLOCK"
    unlock: "GATE UNLOCK"
  display-format:
    - ""
    - "![000/P0000/Y0004/%s%s!]"
    - "![000/P0001/S1000/Y0408/E0606/%s%s!]"

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework: info
    org.springframework.web : info
    root: info

#    gpms-url: "http://ec2-54-180-8-134.ap-northeast-2.compute.amazonaws.com:7000"