server:
  port: 9999

spring:
  profiles:
    active: default
  server-config:
    gpms-url: "http://ec2-54-180-8-134.ap-northeast-2.compute.amazonaws.com:7000"
    ngis-url: "http://localhost:7777"
    server-key: "GATESVR1"
    file-err-path: "C:\\park\\error"
    schedule-time: 30
    breaker-command:
      open: "GATE UP"
      close: "GATE DOWN"
      upLock: "GATE UPLOCK"
      unLock: "GATE UNLOCK"
      health: "STATUS"

  mvc:
    throw-exception-if-no-handler-found: true

management:
  endpoints:
    web:
      exposure:
        include: "info"



---

spring:
  profiles:
    active: dev
  server-config:
    gpms-url: "http://192.168.20.6:11000"
    ngis-url: "http://localhost:7777"
    server-key: "GATESVR1"
    schedule-time: 30
    file-err-path: "C:\\park\\error"
    breaker-command:
      open: "GATE UP"
      close: "GATE DOWN"
      upLock: "GATE UPLOCK"
      unLock: "GATE UNLOCK"

    mvc:
      throw-exception-if-no-handler-found: true

management:
  endpoints:
    web:
      exposure:
        include: "*"