spring:
  profiles:
    active: staging
  mvc:
    throw-exception-if-no-handler-found: true

server-config:
  gpms-url: "http://localhost:13000"
  ngis-url: "http://localhost:7777"
  server-key: "GATESVR1"
  check-time: 30
  breaker-command:
    open: "GATE UP"
    close: "GATE DOWN"
    uplock: "GATE UPLOCK"
    unlock: "GATE UNLOCK"
    health: "STATUS"

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework: info
    org.springframework.web : info
    root: info