server:
  port: 9999

spring:
  profiles:
    active: prod
  server-config:
    gpms-url: ""
    ngis-url: ""
    server-key: "GATESVR1"
    file-err-path: "C:\\park\\error"
    check-time: 30
    breaker-command:
      open: "GATE UP"
      close: "GATE DOWN"
      upLock: "GATE UPLOCK"
      unLock: "GATE UNLOCK"
      health: "STATUS"

  mvc:
    throw-exception-if-no-handler-found: true

management:
  endpoints:
    web:
      exposure:
        include: "info"

logging:
  level:
    org.springframework: info
    org.springframework.web : info
    root: info


---

spring:
  profiles: local
  server-config:
    gpms-url: "http://192.168.20.6:11000"
    ngis-url: "http://localhost:7777"
    server-key: "GATESVR1"
    check-time: 30
    file-err-path: "C:\\park\\error"
    breaker-command:
      open: "GATE UP"
      close: "GATE DOWN"
      uplock: "GATE UPLOCK"
      unlock: "GATE UNLOCK"

    mvc:
      throw-exception-if-no-handler-found: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework: info
    org.springframework.web : info
    root: info


---
spring:
  profiles: staging
  server-config:
    gpms-url: "http://localhost:13000"
    ngis-url: "http://localhost:7777"
    server-key: "GATESVR1"
    check-time: 30
    file-err-path: "C:\\park\\error"
    breaker-command:
      open: "GATE UP"
      close: "GATE DOWN"
      uplock: "GATE UPLOCK"
      unlock: "GATE UNLOCK"

    mvc:
      throw-exception-if-no-handler-found: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework: info
    org.springframework.web : info
    root: info
